version: '3.8'

services:
  app:
    build: ./
    ports:
      - 8080:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=easy_files
    restart: always

